[package]
org = "gayaldassanayake"
name = "hospital_user"
version = "0.1.0"
distribution = "2201.9.1"

[build-options]
observabilityIncluded = true

[[dependency]]
org="gayaldassanayake"
name = "hospital_client"
version="0.1.0"
repository="local"
