[package]
org = "gayaldassanayake"
name = "inventory_user"
version = "0.1.0"
distribution = "2201.9.2"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "aerospace"
name = "inventory"
version = "0.1.0"
repository = "local"
